version: 2.1

jobs:
  build:
    docker:
      - image: quay.io/helmpack/chart-testing:latest
    steps:
      - checkout
      - run:
          name: lint
          command: |
            git remote add k8s $CIRCLE_REPOSITORY_URL
            git fetch k8s $CIRCLE_BRANCH
            ct lint --config .circleci/chart-testing.yaml

